### ISSUE TITLE
write section about verification tests

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/obc#34]
This issue is to write a section about the verification tests.

**Comment by milicag** [comment]
@mwetter I've added a basic description of the verification example. The models I've used are:
* [CLD specification](https://github.com/lbl-srg/obc/blob/issue29_validation_example/examples/validation_example/OBCSequenceValidation/CoolingCoilValve.mo)
* [Modelica verification model](https://github.com/lbl-srg/obc/blob/issue29_validation_example/examples/validation_example/OBCSequenceValidation/Examples/CoolingCoilValve_Trends.mo)

I was having some issues building the html, so optical edits may be needed. I also don't know what you had in mind in terms of embedding the html plots - should I just generate a png for this document?

Let me know what needs edits. I'll tidy the scv2mos script a bit, so that we can upload it. The verification model has the new unit converters, please let me know how they look to you.

**Comment by milicag** [comment]
On practical usability of the verification model.

What came up is that some of the parameters also need unit conversion (e.g. cutoff temperature). I can't use the converter unless I pass the value as an input. I've set up the CDL specification so that such parameters contain a formula that includes the original value. It's probably fine for demo purposes, but likely needs improvement and some thought.

**Comment by mwetter** [comment]
@milicag I revised the description and committed the changes and new figures. 
Can you please address the following:
- [x] redo the Modelica model graphics, download them as svg from dymola, and convert to png and pdf as we did for all other Modelica graphics.
- [x] In the verification, you use greEquThr with a test against ">= 1". You should use ">= 0.5", otherwise floating point errors will cause problems. Please change this.
- [x] Comment on the differences between the anti-windup implementations. They are different, but it seems to have little effect on the results.

**Comment by milicag** [comment]
Sounds good.

**Comment by milicag** [comment]
@mwetter I've addressed the tasks, with the modifications to the third task, as discussed. I also pushed up an updated html plot. What method do you use to convert it to pdf?

**Comment by mwetter** [comment]
From plotly, I think you will need to make a printscreen as it has no svg
or pdf output capability.

**Comment by milicag** [comment]
I printed a pdf from the browser. I bet we can automate this somehow.
